# Generated by Django 3.2.3 on 2021-05-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
